package bst;

import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Botoes
     */
    public Menu(ArvoreBinaria<String, Integer> tree) {
        initComponents(tree);
    	setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(ArvoreBinaria<String, Integer> tree) {

        grupoBotoes = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        consultaChave = new javax.swing.JRadioButton();
        tamArvore = new javax.swing.JRadioButton();
        alturaArvore = new javax.swing.JRadioButton();
        defDepth = new javax.swing.JRadioButton();
        internalPathLength = new javax.swing.JRadioButton();
        imprimeInOrdem = new javax.swing.JRadioButton();
        imprimePreOrdem = new javax.swing.JRadioButton();
        imprimePosOrdem = new javax.swing.JRadioButton();
        botaoConfirma = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setResizable(false);

        jPanel1.setToolTipText("");

        grupoBotoes.add(consultaChave);
        consultaChave.setText("Consultar Chave");
        consultaChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaChaveActionPerformed(evt);
            }
        });

        grupoBotoes.add(tamArvore);
        tamArvore.setText("Tamanho da Arvore");

        grupoBotoes.add(alturaArvore);
        alturaArvore.setText("Altura da Arvore");

        grupoBotoes.add(defDepth);
        defDepth.setText("Definir profundidades");

        grupoBotoes.add(internalPathLength);
        internalPathLength.setText("Comprimento interno");

        grupoBotoes.add(imprimeInOrdem);
        imprimeInOrdem.setText("Imprimir em ordem");

        grupoBotoes.add(imprimePreOrdem);
        imprimePreOrdem.setText("Imprimir pre ordem");

        grupoBotoes.add(imprimePosOrdem);
        imprimePosOrdem.setText("Imprimir pos ordem");
        imprimePosOrdem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimePosOrdemActionPerformed(evt);
            }
        });

        botaoConfirma.setText("OK");
        botaoConfirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoConfirmaMouseClicked(evt, tree);
            }
        });

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tamArvore)
                    .addComponent(alturaArvore)
                    .addComponent(defDepth)
                    .addComponent(consultaChave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(internalPathLength, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imprimeInOrdem)
                    .addComponent(imprimePreOrdem)
                    .addComponent(imprimePosOrdem))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botaoSair)
                .addGap(18, 18, 18)
                .addComponent(botaoConfirma)
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaChave)
                    .addComponent(internalPathLength))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tamArvore)
                    .addComponent(imprimeInOrdem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alturaArvore)
                    .addComponent(imprimePreOrdem))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imprimePosOrdem)
                    .addComponent(defDepth))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoConfirma)
                    .addComponent(botaoSair))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>                     

    private void consultaChaveActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void imprimePosOrdemActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               
	
    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {                                          
        System.exit(0);
    }                                         
	
    private void botaoConfirmaMouseClicked(java.awt.event.MouseEvent evt, ArvoreBinaria<String, Integer> tree) {  
    	String chave;
        if(consultaChave.isSelected()){
        	chave = JOptionPane.showInputDialog("Chave:");
			JOptionPane.showMessageDialog(null, tree.get(chave));
        }else if(tamArvore.isSelected()){
        	JOptionPane.showMessageDialog(null, "Tamanho: "+tree.size());
        }else if(alturaArvore.isSelected()){
        	JOptionPane.showMessageDialog(null, "Altura da arvore: "+tree.height());
        }else if(defDepth.isSelected()){
        	tree.setDepthField();
			JOptionPane.showMessageDialog(null, "Profundidades dos nós definidas!");
        }else if(internalPathLength.isSelected()){
			if(tree.internalPathLength()==0 && tree.size()>1) {
				JOptionPane.showMessageDialog(null, "Defina as profundidades antes de consultar o comprimento interno!",
						"Alerta", JOptionPane.ERROR_MESSAGE);
				return;
			}
			JOptionPane.showMessageDialog(null, "Comprimento interno: "+tree.internalPathLength());
        }else if(imprimeInOrdem.isSelected()){
			JOptionPane.showMessageDialog(null, tree.toString(2));
        }else if(imprimePosOrdem.isSelected()){
        	JOptionPane.showMessageDialog(null, tree.toString(3));
        }else if(imprimePreOrdem.isSelected()){
        	JOptionPane.showMessageDialog(null, tree.toString(1));
        }else{
        	JOptionPane.showMessageDialog(null, "Nenhuma opcao selecionada!",
					"Alerta", JOptionPane.ERROR_MESSAGE);
        }
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[], ArvoreBinaria<String, Integer> tree) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    	
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(tree).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JRadioButton alturaArvore;
    private javax.swing.JButton botaoConfirma;
    private javax.swing.JButton botaoSair;
    private javax.swing.JRadioButton consultaChave;
    private javax.swing.JRadioButton defDepth;
    private javax.swing.ButtonGroup grupoBotoes;
    private javax.swing.JRadioButton imprimeInOrdem;
    private javax.swing.JRadioButton imprimePosOrdem;
    private javax.swing.JRadioButton imprimePreOrdem;
    private javax.swing.JRadioButton internalPathLength;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton tamArvore;
    // End of variables declaration                   
}
